In [2]:
import pandas as pd
import numpy as np


In [3]:
np.random.seed(42)
n_rows=1000
data={'color':np.random.choice(['red','blue','green'],n_rows),
    'size':np.random.choice(['small','medium','large'],n_rows),
    'material':np.random.choice(['plastic','metal','wood'],n_rows),
    'price':np.random.randint(10,500,n_rows)
}
df=pd.DataFrame(data)


In [4]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

In [5]:
!pip install  category_encoders

label encoder

In [6]:
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder

In [7]:
X=df.drop(columns="price")
y=df.price

In [8]:
xtrain,xtest,train,ytest = train_test_split(X,y,random_state=42,train_size=0.8)


In [9]:
label_e=LabelEncoder()

In [10]:
# updated_xtrain = label_e.fit_transform(xtrain) 
# ValueError: y should be a 1d array, got an array of shape (800, 3) instead.


In [11]:
label_e.fit_transform(xtrain['color'])

array([1, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 1,
       2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1,
       2, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2,
       1, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1,
       2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 0, 1, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0,
       0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 0, 2, 1,
       0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 1, 0, 2, 0, 2, 2, 0, 0, 1, 2, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 2, 2, 2, 2, 2, 1, 0, 2, 0, 0, 1, 2, 2,

In [12]:
# label_e.transform(xtest)
# ValueError: y should be a 1d array, got an array of shape (200, 3) instead.

In [13]:
new_input=['red','red']
label_e.transform(new_input)

array([2, 2])

oneHot encoder

In [14]:
ohe=OneHotEncoder()
values=ohe.fit_transform(xtrain)
values=values.toarray()
columns=ohe.get_feature_names_out()

In [15]:
pd.DataFrame(values,columns=columns)

,color_blue,color_green,color_red,size_large,size_medium,size_small,material_metal,material_plastic,material_wood
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...
795,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
796,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
797,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
798,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0


In [16]:
# values = ohe.fit_transform([['color']])
# values = values.toarray()


In [17]:
ohe=OneHotEncoder(sparse_output=False)
values=ohe.fit_transform(xtrain)
values

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [18]:
# onehot_encoder.transform(xtest[['color','size']]) ValueError: The feature names should match those that were passed during fit.
# Feature names seen at fit time, yet now missing:
# - material

In [19]:
ohe.transform(xtest)

array([[0., 0., 1., ..., 1., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [20]:
# unknown values
# new_input = [['red','large'],['blue','small']] #ValueError: X has 2 features, but OneHotEncoder is expecting 3 features as input.
# onehot_encoder.transform(new_input)

In [21]:
new_input = [['red','large','plastic'],['blue','small','wood']]
ohe.transform(new_input)

c:\Users\Hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [22]:
# new_input = [['red','large','rubber'],['blue','small','wood']] #ValueError: Found unknown categories ['rubber'] in column 2 during transform
# onehot_encoder.transform(new_input)

In [23]:
onehot_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
updated_xtrain = onehot_encoder.fit_transform(xtrain)
new_input = [['red1','large','plastic'],['blue','small','wood']] 
onehot_encoder.transform(new_input)

c:\Users\Hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [24]:
onehot_encoder.get_feature_names_out()

array(['color_blue', 'color_green', 'color_red', 'size_large',
       'size_medium', 'size_small', 'material_metal', 'material_plastic',
       'material_wood'], dtype=object)

ordinal encoder

In [27]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
updated_xtrain=encoder.fit_transform(xtrain)
updated_xtrain


array([[1., 2., 2.],
       [0., 1., 0.],
       [0., 2., 2.],
       ...,
       [0., 0., 1.],
       [0., 2., 1.],
       [1., 2., 1.]])

In [28]:
encoder.get_feature_names_out

<bound method OneToOneFeatureMixin.get_feature_names_out of OrdinalEncoder()>

In [30]:
# encoder.fit_transform(xtrain['color'])
# 
# ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [33]:
updated_xtest=encoder.transform(xtest)
updated_xtest

# updated_xtest=encoder.transform(xtest['color'])
# updated_xtest
# ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.


c:\Users\Hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but OrdinalEncoder was fitted without feature names
  warnings.warn(


array([[2., 2., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 2., 1.],
       [0., 1., 0.],
       [2., 0., 1.],
       [1., 0., 1.],
       [2., 2., 1.],
       [2., 0., 0.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [2., 0., 1.],
       [0., 1., 2.],
       [1., 2., 0.],
       [2., 0., 0.],
       [1., 1., 2.],
       [2., 0., 1.],
       [2., 0., 2.],
       [0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 2., 1.],
       [0., 1., 1.],
       [2., 1., 1.],
       [0., 1., 2.],
       [1., 0., 0.],
       [2., 2., 0.],
       [0., 2., 0.],
       [1., 1., 1.],
       [2., 1., 0.],
       [2., 0., 2.],
       [0., 2., 0.],
       [1., 2., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [2., 2., 2.],
       [2., 1., 1.],
       [2., 1., 0.],
       [1., 0., 0.],
       [2., 2., 2.],
       [2., 1., 2.],
       [1., 0., 0.],
       [2., 0., 1.],
       [0., 0., 1.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 2

In [35]:
# new_input = [['red','large','rubber'],['blue','small','wood']]
# encoder.transform(new_input)

# ValueError: Found unknown categories ['rubber'] in column 2 during transform

how to handle unknown values in ordinal encoder 

In [37]:
# encoder=OrdinalEncoder(handle_unknown='error')
encoder=OrdinalEncoder(handle_unknown='use_encoded_value',unknown_value=-1)

In [41]:
updated_xtrain=encoder.fit_transform(xtrain)
updated_xtest=encoder.transform(xtest)
# new_data=[['white','small','wood'],['red','small','wood']]
new_data=pd.DataFrame(data=[['white','small','wood'],['red','small','wood']],columns=['color','size','material'])
updated_new_data=encoder.transform(new_data)
updated_new_data

array([[-1.,  2.,  2.],
       [ 2.,  2.,  2.]])